#!/usr/bin/env php
<?php

declare(strict_types=1);

namespace ControlStructureTest;

use ControlStructureTest\TestRunning\Runner;
use ControlStructureTest\TestPrinting\{
    Printer,
    Configuration\PrintResultConfig
};

/* nested files first since they are dependencies */
array_map(function ($file) { require $file; }, glob("*/*/*.php"));
/* then.. */
array_map(function ($file) { require $file; }, glob("*/*.php"));

$testCaseArguments = (include "test_case_arguments.php");

[$results_to_print, $test_iterations, $execution_time_for_tests] =
    Runner::runAllTestsWith(...$testCaseArguments);

Printer::printTestResultsUsing(new PrintResultConfig($results_to_print, $test_iterations, $execution_time_for_tests));
