#!/usr/bin/env php
<?php

declare(strict_types=1);

/* nested files first */
array_map(function ($file) { require $file; }, glob('**/**/*.php'));
/* then files with the functions that run tests */
array_map(function ($file) { require $file; }, glob('**/*.php'));

$testCaseArguments =
    getTestCases();

[$results_to_print, $test_iterations, $execution_time_for_tests] =
    runAllTests(...$testCaseArguments);

printTestResults($results_to_print, $test_iterations, $execution_time_for_tests);
