#!/usr/bin/env php
<?php

declare(strict_types=1);

namespace ControlStructureTest;

use ControlStructureTest\TestRunning\Runner;
use ControlStructureTest\TestPrinting\{
    Printer,
    Configuration\PrintResultConfig
};

/**
 * Make this script callable from anywhere without changing it's behavior
 */
chdir(__DIR__);
/**
 *  Nested files first since they are dependencies
 */
array_map(fn ($file) => require $file, glob("*/*/*.php"));
/*
 * Then...
 */
array_map(fn ($file) => require $file, glob("*/*.php"));
/*
 * Retrieve the arguments for the tests
 */
$test_case_arguments = include "test_case_arguments.php";
/*
 * Run tests and print results
 */
$result_information = Runner::runAllTestsWith(...$test_case_arguments);
$printer_config = new PrintResultConfig(...$result_information);
Printer::printTestResultsUsing($printer_config);
